# Generated by Django 4.0.2 on 2022-08-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ölçü', models.CharField(max_length=200, null=True)),
                ('giriş', models.CharField(default='', max_length=200, null=True)),
                ('yükseklik', models.CharField(default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.ManyToManyField(default='', null=True, to='banyo.Size')),
            ],
        ),
    ]
