# Generated by Django 4.0.2 on 2022-08-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sarı', 'Sarı'), ('altın', 'altın'), ('kırmızı', 'kırmızı'), ('yeşil', 'yeşil'), ('mavi', 'mavi')], max_length=200, null=True)),
                ('color_image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='acilis_sekli',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='product',
            name='giriş',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='yükseklik',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='özellikler',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category_size', models.ManyToManyField(default='', null=True, to='banyo.Size')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(default='', null=True, related_name='color', to='banyo.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(default='', null=True, related_name='size', to='banyo.Category'),
        ),
    ]
