# Generated by Django 4.0.2 on 2022-08-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0002_color_product_acilis_sekli_product_giriş_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ManyToManyField(default='', null=True, related_name='size', to='banyo.Category'),
        ),
    ]
