# Generated by Django 4.0.2 on 2022-08-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0003_remove_product_size_product_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='giriş',
        ),
        migrations.RemoveField(
            model_name='product',
            name='yükseklik',
        ),
    ]
