# Generated by Django 4.0.2 on 2022-08-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0004_remove_product_giriş_remove_product_yükseklik'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category_size', models.ManyToManyField(default='', null=True, to='banyo.Size')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(default='', null=True, related_name='type', to='banyo.Product_model'),
        ),
    ]
