# Generated by Django 4.0.2 on 2022-08-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0005_product_model_remove_product_cat_delete_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alt_kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('alt_kategoriler', models.ManyToManyField(default='', null=True, related_name='alt_kategori', to='banyo.Alt_kategori')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alt_kategori', to='banyo.alt_kategori'),
        ),
    ]
