# Generated by Django 4.0.2 on 2022-08-23 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0006_alt_kategori_category_product_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alt_kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alt_kategori', to='banyo.alt_kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='banyo.category'),
        ),
    ]
