# Generated by Django 4.0.2 on 2022-08-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0007_product_alt_kategori_alter_product_kategori'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Sarı', 'Sarı'), ('altın', 'altın'), ('kırmızı', 'kırmızı'), ('yeşil', 'yeşil'), ('mavi', 'mavi')], max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='montaj_sekli',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='montaj', to='banyo.montaj'),
        ),
    ]
