# Generated by Django 4.0.2 on 2022-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0008_montaj_product_montaj_sekli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='montaj',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
