# Generated by Django 4.0.2 on 2022-08-23 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0009_alter_montaj_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False, unique=True),
        ),
    ]
