# Generated by Django 4.0.2 on 2022-08-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0010_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='abc', editable=False, unique=True),
        ),
    ]
