# Generated by Django 4.0.2 on 2022-08-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0013_product_çoks_satan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(null=True, upload_to='image/references')),
                ('proje_adi', models.CharField(max_length=200, null=True)),
                ('firma', models.CharField(max_length=200, null=True)),
                ('adres', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
