# Generated by Django 4.0.2 on 2022-08-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0014_referans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hakkimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciklama', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
