# Generated by Django 4.0.2 on 2022-08-24 20:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0015_hakkimizda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hakkimizda',
            name='aciklama',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
