# Generated by Django 4.0.2 on 2022-08-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0016_alter_hakkimizda_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='Katalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katalog_resim', models.ImageField(null=True, upload_to='image/')),
                ('katalog_dosyasi', models.FileField(upload_to='files/')),
            ],
        ),
    ]
