# Generated by Django 4.0.2 on 2022-08-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0017_katalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='çoks_satan',
        ),
        migrations.AddField(
            model_name='product',
            name='görüntüleme',
            field=models.IntegerField(default=0),
        ),
    ]
