# Generated by Django 4.0.2 on 2022-08-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0018_remove_product_çoks_satan_product_görüntüleme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musteri_ismi', models.CharField(max_length=100, null=True, verbose_name='Ad Soyad')),
                ('mesaj', models.TextField(max_length=500, null=True, verbose_name='Yorum')),
                ('mail', models.EmailField(max_length=100, null=True)),
                ('telefon', models.CharField(max_length=12, null=True, verbose_name='telefon')),
            ],
        ),
    ]
