# Generated by Django 4.0.2 on 2022-08-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0021_ölçüler_delete_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ürün_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('category_size', models.ManyToManyField(default='', null=True, to='banyo.Ölçüler')),
            ],
        ),
        migrations.DeleteModel(
            name='Product_model',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ManyToManyField(default='', null=True, related_name='type', to='banyo.Ürün_model'),
        ),
    ]
