# Generated by Django 4.0.2 on 2022-08-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0023_kategoriler_alter_product_kategori_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Renkler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('color_image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(default='', null=True, related_name='color', to='banyo.Renkler'),
        ),
    ]
