# Generated by Django 4.0.2 on 2022-08-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0025_mesajlar_montaj_tipi_referanslar_ürün_delete_mesaj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriler',
            name='alt_kategoriler',
            field=models.ManyToManyField(default='', related_name='alt_kategori', to='banyo.Alt_kategori'),
        ),
        migrations.AlterField(
            model_name='ürün',
            name='color',
            field=models.ManyToManyField(default='', related_name='color', to='banyo.Renkler'),
        ),
        migrations.AlterField(
            model_name='ürün',
            name='product_type',
            field=models.ManyToManyField(default='', related_name='type', to='banyo.Ürün_model'),
        ),
        migrations.AlterField(
            model_name='ürün_model',
            name='category_size',
            field=models.ManyToManyField(default='', to='banyo.Ölçüler'),
        ),
    ]
