# Generated by Django 4.0.2 on 2022-08-26 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0026_alter_kategoriler_alt_kategoriler_alter_ürün_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alt_kategoriler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='kategoriler',
            name='alt_kategoriler',
            field=models.ManyToManyField(default='', related_name='alt_kategori', to='banyo.Alt_kategoriler'),
        ),
        migrations.AlterField(
            model_name='ürün',
            name='alt_kategori',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Alt_kategori', to='banyo.alt_kategoriler'),
        ),
        migrations.DeleteModel(
            name='Alt_kategori',
        ),
    ]
