# Generated by Django 4.0.2 on 2022-08-27 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0029_hakkimizda_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategoriler',
            name='alt_kategoriler',
        ),
    ]
