# Generated by Django 4.0.2 on 2022-09-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0030_remove_kategoriler_alt_kategoriler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giris_resimleri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim1', models.ImageField(null=True, upload_to='image/')),
                ('resim2', models.ImageField(null=True, upload_to='image/')),
                ('resim3', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
    ]
