# Generated by Django 4.0.2 on 2022-09-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banyo', '0031_giris_resimleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='giris_resimleri',
            name='logo',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
